config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  resources :channels, only: %i[index show] do
    resources :messages, only: %i[create index edit update]
  end

  root 'messages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
# frozen_string_literal: true

class Channel < ApplicationRecord
  validates :title, presence: true,
                    uniqueness: true,
                    length: { maximum: 100 },
                    format: {
                      with: /\A[a-zA-Z0-9\-_]+\z/,
                      message: 'only allows letters, numbers, dashes, and underscores'
                    }

  has_many :messages

  default_scope { order(:title) }
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  has_paper_trail

  belongs_to :user
  belongs_to :channel

  validates :body, presence: true

  default_scope { order(created_at: :asc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_many :messages
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

class ChannelsController < ApplicationController
  def index
    redirect_to root_path
  end

  def show
    redirect_to channel_messages_path(params[:id])
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_channel, except: [:home]
  before_action :set_messages, only: %i[index edit]

  def index
    @message = Message.new
  end

  def edit
    @message = current_user.messages.where(id: params[:id], channel: @channel).first

    if @message.nil?
      redirect_to channel_messages_path(@channel),
                  alert: 'You can only edit your own messages from this channel.'
    end

    render :index
  end

  def create
    @message = Message.new(create_params)
    if @message.save
      redirect_to channel_messages_path(@channel), notice: 'Message was created successfully.'
    else
      set_messages
      render :index
    end
  end

  def update
    @message = current_user.messages.where(id: params[:id], channel: @channel).first

    if @message.nil?
      redirect_to channel_messages_path(@channel),
                  alert: 'You can only edit your own messages from this channel.'
    end

    if @message.update(message_params)
      redirect_to channel_messages_path(@channel), notice: 'Message was updated successfully.'
    else
      set_messages
      render :index
    end
  end

  def home
    redirect_to channel_messages_path(Channel.first)
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def create_params
    message_params.merge(channel: @channel, user: current_user)
  end

  def set_channel
    @channel = Channel.find(params[:channel_id])
  end

  def set_messages
    @messages = @channel.messages.includes(:user, :versions)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/channels_helper.rb
# frozen_string_literal: true

module ChannelsHelper
  def channel_link_classes(channel)
    classes = %w[block px-6 py-1 no-underline duration-300 transition-colors]

    classes << if channel == @channel
                 %w[bg-pink-600 text-white]
               else
                 %w[text-stone-400 hover:bg-stone-900 hover:text-stone-300]
               end

    classes.join(' ')
  end
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
  def message_group(message)
    return 'Today' if message.created_at.today?
    return 'Yesterday' if message.created_at.yesterday?

    message.created_at.strftime('%B %-d, %Y')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Edited State | Ultimate PaperTrail Guide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path("favicon.png") %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body class="bg-stone-50">
    <% if notice || alert %>
      <div class="fixed left-0 z-50 w-full text-center text-white top-2" data-fade-out>
        <% if notice %>
          <p class="inline-block px-3 py-2 mb-0 bg-blue-500 rounded-md"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="inline-block px-3 py-2 mb-0 bg-red-500 rounded-md"><%= alert %></p>
        <% end %>
      </div>
    <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>
<script>
  $(document).ready(function() {
    setTimeout(function() {
      $('[data-fade-out]').fadeOut(1000);
    }, 2500);
  });
</script>

app/views/messages/index.html.erb
<div class="flex h-screen">
  <%# --- Channels (Left Col) --- %>
  <div class="text-white bg-stone-800 min-w-[20rem]">
    <div class="px-8 py-6 border-b border-stone-600">
      <h2 class="mb-1 text-sm font-extralight">Ultimate PaperTrail Guide</h2>
      <h1 class="mb-0 text-2xl font-bold">Edited State Example</h1>
    </div>
    <div class="py-4">
      <h2 class="mx-6 mb-4 text-sm font-extralight">Channels</h2>
      <nav>
        <% Channel.all.each do |channel| %>
          <%= link_to "##{channel.title}", channel_messages_path(channel), class: channel_link_classes(channel) %>
        <% end %>
      </nav>
    </div>
  </div>
  <%# --- Messages (Right Col) --- %>
  <div class="relative flex-grow">
    <%# --- Header --- %>
    <div class="absolute top-0 left-0 right-0 z-10">
      <div class="flex items-center justify-between w-full px-4 py-3 mx-auto bg-white border-b border-gray-200">
        <div>
          <span class="font-bold">#<%= @channel.title %></span>
        </div>
        <div class="flex items-center space-x-2">
          <% if user_signed_in? %>
            <div class="flex-shrink-0">
              <%= image_tag "https://i.pravatar.cc/400?img=#{current_user.id}", class: "rounded-full h-8 w-8 border border-stone-300" %>
            </div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-sm no-underline hover:underline' %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: 'text-sm no-underline hover:underline' %>
          <% end %>
        </div>
      </div>
    </div>
    <%# --- Messages --- %>
    <div class="relative z-0 h-full pt-16 pb-20 overflow-y-scroll">
      <% @messages.group_by { |x| message_group(x) }.each do |date, messages| %>
        <div class="relative my-4 text-center">
          <div class="w-full h-[1px] bg-stone-200 absolute top-[12px]"></div>
          <span class="relative inline-block px-3 py-1 mx-auto text-xs border rounded-full bg-gray-50 border-stone-400"><%= date %></span>
        </div>
        <% messages.each do |message| %>
          <div class="flex px-4 mb-6 space-x-2" id="message-<%= message.id %>">
            <div class="flex-shrink-0 mt-1">
              <%= image_tag "https://i.pravatar.cc/400?img=#{message.user.id}", class: "rounded-lg h-10 w-10" %>
            </div>
            <div class="relative flex-grow">
              <div class="flex items-center mb-1 space-x-2 text-sm">
                <span class="font-bold "><%= message.user.name %></span>
                <span class="text-stone-500"><%= message.created_at.to_fs(:time) %></span>
                <% if message.versions.select { |v| v.event == 'update' }.size > 0 %>
                  <span class="px-1 py-[2px] text-xs text-blue-400 uppercase bg-blue-100 border border-blue-200 rounded-sm">Edited</span>
                <% end %>
              </div>
              <div class="flex-grow">
                <%= message.body %>
              </div>
              <% if message.user == current_user %>
                <div class="absolute top-[-.35rem] right-4">
                  <%= link_to 'Edit', edit_channel_message_path(@channel, message), class: 'text-xs p-2 border border-stone-300 text-stone-500 uppercase no-underline rounded-md hover:text-pink-500 hover:border-pink-500 duration-300 transition-colors' %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%# --- New Message Form --- %>
    <div class="absolute bottom-0 left-0 right-0 z-10 bg-white border-t border-stone-300">
      <%= simple_form_for [@channel, @message], html: { class: 'relative'} do |f| %>
        <%= f.input :body, label: false, placeholder: 'New message ...' %>
        <%= f.submit 'Send', class: 'bg-blue-500 absolute right-4 top-3 text-sm text-white rounded-md py-2 px-4' %>
      <% end %>
    </div>
  </div>
</div>
<%# Scroll to latest message %>
<script type="text/javascript">
  var lastMessage = document.getElementById("message-<%= @messages.last.id %>");
  lastMessage.scrollIntoView();
</script>